apiVersion: v1
kind: Service
metadata:
  labels:
   app: kong-admin
  name: kong-admin
  namespace: kong
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: ingress-kong


