apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
 name: tcp-log
 annotations:
  kubernetes.io/ingress.class: kong
 labels:
  global: 'true'
plugin: tcp-log
config:
 host: logstash.elk.svc.cluster.local
 port: 5043
