apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: jenkins
 name: jenkins-home
spec:
 storageClassName: jenkins-home
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 8Gi
