apiVersion: v1
kind: PersistentVolume
metadata:
 name: jenkins-home
 namespace: jenkins
spec:
 storageClassName: jenkins-home
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 8Gi
 nodeAffinity:
  required:
   nodeSelectorTerms:
   - matchExpressions:
     - key: jenkins-node
       operator: In
       values:
        - 'true'
 hostPath:
  path: /data/jenkins/home
