apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
spec:
  storageClassName: redis-data
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: redis
  name: redis-data
spec:
  storageClassName: redis-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 8Gi